### ISSUE TITLE
Calendar styling is off with dark theme

### ISSUE THREAD

**Issue by cadamsdev** [leenzhu/joplin-plugin-journal#10]
Change the theme to "Dark".

- Month and year are too dark
- Next/Prev buttons are too dark
- Calendar days are too bright (should use darker buttons with lighter text)

![image](https://user-images.githubusercontent.com/12568665/203880074-2c2e794a-8292-4da2-b166-34277b7a50c8.png)

**Comment by leenzhu** [comment]
Thanks for your feedback.

I don't known how to change the calendar theme according to different joplin theme, I'm trying to use  neutral colors for both dark and bright themes. But I'm not good at color mathing neither, any suggestions?
