### ISSUE TITLE
Feature Request: Open today's note on application startup

### ISSUE THREAD

**Issue by cmagin** [leenzhu/joplin-plugin-journal#12]
I would really like to open today's note on application start, since I tend to forget to write things in there. I've tried Obsidian before Joplin, and Obsidian had a plugin very similar to this one with the option to open today's note (or create it when not existing) on startup. Would there be any chance for an option like this?

**Comment by leenzhu** [comment]
Check the new version latter

**Comment by leenzhu** [comment]
Sorry, it seems not work in production mode, it reports:

> Error: Cannot execute a command without a runtime: openNote

It works ok in develop mode, I don't know why.

**Comment by leenzhu** [comment]
Perhaps I've fix it, you can have a try.

**Comment by cmagin** [comment]
Just tried it, thank you very much!
