### ISSUE TITLE
Bug report: opening the calendar but not selecting a day but then hitting ok creates a file called 'NaN-aN-aN'

### ISSUE THREAD

**Issue by ethancedwards8** [leenzhu/joplin-plugin-journal#18]
# Steps to reproduce
1. Hit control + alt + o
2. Do not select a day
3. Hit ok
4. See the file in your journal directory

# Expected behaviour 
Giving a warning or prompting the user to choose a day

**Comment by leenzhu** [comment]
@ethancedwards8 Thanks, I'll check this issue latter.
