### ISSUE TITLE
Unclear warning in the Readme

### ISSUE THREAD

**Issue by narFnarF** [leenzhu/joplin-plugin-journal#19]
In the [Readme file](https://github.com/leenzhu/joplin-plugin-journal#important), it's written: 

> Important: Use the insert note link feature carefully, because it will mean that the editor is NOT able to UNDO.

I'm not sure what this means. Can you explain?

**Comment by leenzhu** [comment]
I meant that when the link being inserted, the UNDO stack seems to be cleared, just like that when you are editing current note and then swaping to open another note and then swaping back, you'll see that you can't UNDO any thing.

Sorry, I couldn't reproduce this now for the old version 2.7.15 and the newer version 2.11.11.

I'll modify the README.

**Comment by leenzhu** [comment]
Remove unclear warning by https://github.com/leenzhu/joplin-plugin-journal/releases/tag/v1.1.0
