### ISSUE TITLE
Can't insert a journal entry for yesterday

### ISSUE THREAD

**Issue by bcook75** [leenzhu/joplin-plugin-journal#2]
Whatever date I choose from the calendar to create a journal entry for, it creates for the day before. Which means I cannot create an entry for "yesterday". The other days I can fudge, but for "yesterday" I have to manually edit the note title.

Otherwise, looking pretty good.

The "default value" for "Note Name Template" as shown in the help text on the config page is not correct. It says the default is "'Journal/{{year}}/{{year}}-{{month}}-{{day}}', but it isn't. As shown on a screenshot somewhere here on Github, the actual default value is "Journal/{{year}}/{{monthName}}/{{year}}-{{month}}-{{day}}.

Bart

**Comment by leenzhu** [comment]
@bcook75 

It's very strange, I'm not sure what happend, perhaps it is related to time zone.  Please visit this page [Vanilla Calendar](https://vanilla-calendar.frontend.uvarov.tech/en/) , and choose different date to check whether the date display correct.

And If there is nothing wrong with vanilla calendar, please open Joplin, and click menu `Help`->`Toggle Development Tools` open the `Console` panel, and input `new Date()`, and then check whether it shows the correct date.

And thanks for point out the mistake of the description, I'll fix it later.
