### ISSUE TITLE
Importing md files with folder structure

### ISSUE THREAD

**Issue by narFnarF** [leenzhu/joplin-plugin-journal#20]
This plugin looks amazing! It looks like exactly what I need! I have a question though.

My current journal consists of a lot of markdown files that are in folders like this:

- 2023
   - Jan
       - 01
       - 02
       - ...
   - Feb
   - ...
- 2022
   - Jan
       - 01
       - 02
       - ...
   - Feb
   - ...

What would be the best way to import all my existing journal into Joplin so that it will be compatible with the journal plugin?

**Comment by leenzhu** [comment]
Have a look at this [link](https://github.com/leenzhu/joplin-plugin-journal/issues/6), hope it will be helpfull.
