### ISSUE TITLE
Default note name template cannot use time elements

### ISSUE THREAD

**Issue by DeanHutchings** [leenzhu/joplin-plugin-journal#21]
The default name template cannot use time elements (hour, min, sec) even though the code appears to support (most of) the functionality.

I would like to name new journal notes with the time as well as the date. The code in index.ts appears to support it, except calls to createNoteByDate() are passed a parameter that is a Date without the time component.

I would like to ask that the Date parameter could include the time portion of the current date/time where possible. I realize that creating a new note based on the user's selection on the calendar dialog cannot provide the time.

Support for hours in 12 hour format and 24 hour format would also be nice. That option doesn't appear possible with the current implementation in makeNoteName().

Thank you for your consideration of this issue.
Dean

**Comment by leenzhu** [comment]
Thanks for the detailed description. 

Actually the calendar dialog has the ability to select time, but I dissabled it. I'll enable it after fix this issue :-)

**Comment by leenzhu** [comment]
@DeanHutchings It was fixed by latest version: https://github.com/leenzhu/joplin-plugin-journal/releases/tag/v1.1.0
