### ISSUE TITLE
[Feature]: ability to see what notes have entries

### ISSUE THREAD

**Issue by danielb2** [leenzhu/joplin-plugin-journal#27]
maybe mark it with a dot below the number to indicate that the calendar has an entry already

**Comment by danielb2** [comment]
I looked at https://vanilla-calendar.pro/docs/reference/main, but it doesn't look like there's a feature for it. What i'm suggesting wouldn't be difficult to do with joplin's api. Just missing the calendar feature for it.

**Comment by danielb2** [comment]
closing for now

**Comment by leenzhu** [comment]
> I looked at https://vanilla-calendar.pro/docs/reference/main, but it doesn't look like there's a feature for it. What i'm suggesting wouldn't be difficult to do with joplin's api. Just missing the calendar feature for it.

Add a dot on a day is easy for vanilla-calendar, but we should know which day need to be marked. The calendar js running inside a dialog, while we couldn't invoke joplin API inside a dialog, so we couldn't get the dates that have notes.

As the #28 implemented, currently, We can only pre-fetch the dates to be displayed from `index.ts` and then pass them into the calendar dialog. However, this approach is time-consuming, not flexible enough, and imposes certain limitations on the data that can be displayed.

**Comment by leenzhu** [comment]
Hi @danielb2,

I'm glade to tell you, the coming version(v1.2.0) would meet your demands.

**Comment by danielb2** [comment]
I'm not seeing the dots

<img width="295" alt="Screenshot 2024-09-06 at 18 05 44" src="https://github.com/user-attachments/assets/89cf5aae-86f7-4a90-bb0d-4a4b37109987">

september 5th has a note

**Comment by leenzhu** [comment]
Hi @danielb2 ,

Did you enable the `Calendar Highlights` in the settings?
![image](https://github.com/user-attachments/assets/387dd2dc-211e-4a24-be89-180f66f4f693)

As you said you have a note on Sep 5th, and is the name of the note consistent with the template structure?

**Comment by danielb2** [comment]
oh I didn't see this. seems like this could be good to be on by default?

**Comment by leenzhu** [comment]
> oh I didn't see this. seems like this could be good to be on by default?

I'm not sure if most people would need this feature. Personally, I prefer a clean and fast functionality. After all, if it's enabled by default, every time the dialog opens, it would trigger numerous query requests, which could be bothersome for those who don't need it. My general approach to adding new features is that if there's a demand, the feature can be enabled proactively; otherwise, nothing is done, as if no update was ever made.
