### ISSUE TITLE
Journal plugin does nothing

### ISSUE THREAD

**Issue by juliux-arg** [leenzhu/joplin-plugin-journal#5]
I've installed journal plugin and does nothing (neither by keyboard shortcut nor by menu).
Notes are encrypted.
OS: Linux Mint 20.3.

**Comment by leenzhu** [comment]
Is there any other plugin working as expected?

The following is my joplin version:

Joplin 2.8.8 (prod, win32)

Client ID: 57b929924c8644f6a5dc4a0c4e96051b
Sync Version: 3
Profile Version: 41
Keychain Supported: Yes

Revision: c2a6a13

**Comment by juliux-arg** [comment]
> Is there any other plugin working as expected?
No other plugins.

Joplin 2.8.8 (prod, linux)

ID del Cliente: fe763aedda734cef8d1b16c62fb9e753
Versión de la Sincronización: 3
Versión del Perfil: 41
Llavero Soportado: No

Revisión: c2a6a13

I'm syncronizing with OneDrive, encrypted mode.
When syncronizing I've observed **/home/juliux/.config/joplin-desktop** directory. It's created a file named as **database.sqlite-journal**, and is immediately deleted automatically.

**Comment by juliux-arg** [comment]
It's solved now. Thanks!!!!!
