### ISSUE TITLE
Feature request: import from Zim Wiki

### ISSUE THREAD

**Issue by juliux-arg** [leenzhu/joplin-plugin-journal#6]
I have a journal in Zim Wiki, and want to import it into Joplin.

**Comment by leenzhu** [comment]
Sorry, I'm not familiar with Zim Wiki, but if your could export your Zim Wiki as the following fold tree:
![image](https://user-images.githubusercontent.com/25599632/196071941-359175f4-b9ed-444e-8b86-3715fcfc70f7.png)

I think think you could import the whole data with joplin's builtin import feature.
![image](https://user-images.githubusercontent.com/25599632/196072246-801acf05-64e8-415d-b08e-83dcb0efda27.png)

**Comment by juliux-arg** [comment]
Yes, I could do it as you told me. Thank you.
